### ISSUE TITLE
New changes to nn.Identity break compatibility with previously saved models (and apparently, some other Torch code)

### ISSUE THREAD

**Issue by jfsantos** [torch/nn#502] opened 2015-11-27 20:02 UTC
`nn.Identity`, as per commit b7a64bf1, has a new field `.tensorOutput` which does not exist in models checkpointed with previous versions. This causes issues loading these modules with the updated code.

Additionally, this update seems to be breaking code such as karpathy/char-rnn and karpathy/neuraltalk2. In char-rnn, for example, I am getting this error the first time `optim.rmsprop` is called:

```
/Users/jfsantos/torch/install/bin/luajit: /Users/jfsantos/torch/install/share/lua/5.1/nn/Identity.lua:13: bad argument #1 to 'set' (expecting number or Tensor or Storage at /tmp/luarocks_torch-scm-1-8315/torch7/generic/Tensor.c:1089)
stack traceback:
	[C]: in function 'set'
	/Users/jfsantos/torch/install/share/lua/5.1/nn/Identity.lua:13: in function 'func'
	...jfsantos/torch/install/share/lua/5.1/nngraph/gmodule.lua:252: in function 'neteval'
	...jfsantos/torch/install/share/lua/5.1/nngraph/gmodule.lua:287: in function 'forward'
	train.lua:270: in function 'opfunc'
	...s/jfsantos/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
	train.lua:314: in main chunk
	[C]: in function 'dofile'
	...ntos/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0103718320
```

**Comment by soumith** [comment] 2015-11-27 20:03
Will fix asap. Sorry about that.

**Comment by karpathy** [comment] 2015-11-27 20:03
Link to a related neuralk2 issue: https://github.com/karpathy/neuraltalk2/issues/14
Link to a related char-rnn issue: https://github.com/karpathy/char-rnn/issues/135

**Comment by soumith** [comment] 2015-11-27 20:41
Should be fixed in master via https://github.com/torch/nn/commit/3fff0c69b16442a6b4438edf5ec939768e580e88

very sorry about that. I'll add tests this weekend for back-compat serialization, so that such issues dont happen in the future.

**Comment by andreaskoepf** [comment] 2015-11-27 20:50
I am trying to reproduce the 'the first time optmi.rmsprop' is called. I have locally a version without the latest patch sumbitted by soumith (about 30 minutes since last update) and it does not show the error - neither on the original char-rnn nor on personal RNN derived stuff.

**Comment by jfsantos** [comment] 2015-11-27 20:56
Maybe that one is related to an interaction with something else (say,
nngraph or optim)? I updated both today and still had that same problem.

I tested this on the latest commit to master of the char-rnn repo. Will
test Soumith's patch right now.

--
João Felipe Santos

**Comment by jfsantos** [comment] 2015-11-27 21:40
I just found out what is breaking char-rnn. In `Identity:__init()`, `self.tensorOutput` is initialized as `torch.Tensor{}` (which usually defaults to `DoubleTensor` or `FloatTensor`), but char-rnn uses `ByteTensor`s as inputs/outputs when running on the CPU (or OpenCL). Maybe the code did not break for @andreaskoepf because he was running it with CUDA? (the code casts the inputs/outputs to float when using CUDA)

**Comment by andreaskoepf** [comment] 2015-11-27 21:46
@jfsantos you are right. `th train.lua -gpuid -1` shows the error without patch.

**Comment by soumith** [comment] 2015-11-27 21:59
Removing the init in the constructor will fix it. I can patch it in a few
hours, not at the computer at the moment. Or someone can send in a pr.

**Comment by jfsantos** [comment] 2015-11-27 22:06
Just did it and it indeed fixes the issue. PR submitted as #504.

**Closed** 2015-11-27 22:45 UTC
